<?php

/**
 * Implements hook_menu().
 */
function login_cidadao_menu() {
  $items['admin/config/people/login-cidadao'] = array(
    'title' => t('Login cidadão configurações'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('login_cidadao_settings_form'),
    'access arguments' => array('administer users'),
    'description' => 'Configurar configurações para login cidadão',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function login_cidadao_settings_form($form, &$form_state) {
  $form['login_cidadao_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Client id'),
    '#default_value' => variable_get('login_cidadao_client_id', NULL),
  );
  $form['login_cidadao_app_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('App secret'),
    '#default_value' => variable_get('login_cidadao_app_secret', NULL),
  );

  return system_settings_form($form);
}
